
package mx.com.gseguros.ws.autosgs.cotizacion.client.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CotizacionIndividualWSService", targetNamespace = "http://com.gs.cotizador.ws.cotizacionindividual", wsdlLocation = "http://10.1.1.134:8000/cotizadoremisorautos-ws/soap/cotizacionIndividualWS?wsdl")
public class CotizacionIndividualWSService
    extends Service
{

    private final static URL COTIZACIONINDIVIDUALWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException COTIZACIONINDIVIDUALWSSERVICE_EXCEPTION;
    private final static QName COTIZACIONINDIVIDUALWSSERVICE_QNAME = new QName("http://com.gs.cotizador.ws.cotizacionindividual", "CotizacionIndividualWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.1.134:8000/cotizadoremisorautos-ws/soap/cotizacionIndividualWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COTIZACIONINDIVIDUALWSSERVICE_WSDL_LOCATION = url;
        COTIZACIONINDIVIDUALWSSERVICE_EXCEPTION = e;
    }

    public CotizacionIndividualWSService() {
        super(__getWsdlLocation(), COTIZACIONINDIVIDUALWSSERVICE_QNAME);
    }

    //public CotizacionIndividualWSService(WebServiceFeature... features) {
        //super(__getWsdlLocation(), COTIZACIONINDIVIDUALWSSERVICE_QNAME, features);
    //}

    public CotizacionIndividualWSService(URL wsdlLocation) {
        super(wsdlLocation, COTIZACIONINDIVIDUALWSSERVICE_QNAME);
    }

    //public CotizacionIndividualWSService(URL wsdlLocation, WebServiceFeature... features) {
        //super(wsdlLocation, COTIZACIONINDIVIDUALWSSERVICE_QNAME, features);
    //}

    public CotizacionIndividualWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    //public CotizacionIndividualWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        //super(wsdlLocation, serviceName, features);
    //}

    /**
     * 
     * @return
     *     returns CotizacionIndividualWS
     */
    @WebEndpoint(name = "CotizacionIndividualWSPort")
    public CotizacionIndividualWS getCotizacionIndividualWSPort() {
        return super.getPort(new QName("http://com.gs.cotizador.ws.cotizacionindividual", "CotizacionIndividualWSPort"), CotizacionIndividualWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CotizacionIndividualWS
     */
    @WebEndpoint(name = "CotizacionIndividualWSPort")
    public CotizacionIndividualWS getCotizacionIndividualWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.gs.cotizador.ws.cotizacionindividual", "CotizacionIndividualWSPort"), CotizacionIndividualWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COTIZACIONINDIVIDUALWSSERVICE_EXCEPTION!= null) {
            throw COTIZACIONINDIVIDUALWSSERVICE_EXCEPTION;
        }
        return COTIZACIONINDIVIDUALWSSERVICE_WSDL_LOCATION;
    }

}
