package mx.com.gseguros.portal.general.util;

public enum Catalogos {
	
	MC_ESTATUS_TRAMITE("STATUSTRA"),//CON_CAT_MESACONTROL_ESTAT_TRAMI
	MC_SUCURSALES_ADMIN("TUNIDECO"),//CON_CAT_MESACONTROL_SUCUR_ADMIN
	MC_SUCURSALES_DOCUMENTO("TUNIDECO"),//CON_CAT_MESACONTROL_SUCUR_DOCU
	MC_TIPOS_TRAMITE("TRAMITES"),//CON_CAT_MESACONTROL_TIP_TRAMI
	MOTIVOS_CANCELACION("TRAZCANC"),//CON_CAT_CANCELA_MOTIVOS
	NACIONALIDAD("TNACIONALIDAD"),//CON_CAT_NACIONALIDAD
	ROLES_POLIZA("TROLES"),//CON_CAT_POL_ROL
	STATUS_POLIZA("STATUSPOL"),//CON_CAT_POL_ESTADO
	TIPOS_PERSONA("TTIPOPERSONA"),//CON_CAT_TPERSONA
	TIPOS_PAGO_POLIZA("TPERPAG"),//CON_CAT_POL_TIPO_PAGO
	TIPOS_POLIZA("TIPOPOL"),//CON_CAT_POL_TIPO_POLIZA
	
	CODIGOS_POSTALES("CODIGOS_POSTALES");

	private String cdTabla;

	private Catalogos(String cdTabla) {
		this.cdTabla = cdTabla;
	}

	public String getCdTabla() {
		return cdTabla;
	}
}