package mx.com.gseguros.portal.general.util;

public enum Catalogos {
	
	AGENTES(""),
	CAUSA_SINIESTRO("TCAUSASSV"),
	CODIGOS_MEDICOS(""),
	COLONIAS(""),
	MC_ESTATUS_TRAMITE("STATUSTRA"),
	MC_SUCURSALES_ADMIN("TUNIDECO"),
	MC_SUCURSALES_DOCUMENTO("TUNIDECO"),
	MC_TIPOS_TRAMITE("TRAMITES"),
	MOTIVOS_CANCELACION("TRAZCANC"),
	MOTIVOS_REEXPEDICION("TRAZREEXP"),
	NACIONALIDAD("TNACIONALIDAD"),
	ROLES_POLIZA("TROLES"),
	SEXO("TSEXO"),
	STATUS_POLIZA("STATUSPOL"),
	TATRISIT("TATRISIT"),
	TATRIPOL("TATRIPOL"),
	TATRIPER("TATRIPER"),
	TATRIGAR("TATRIGAR"),
	TIPO_CONCEPTO_SINIESTROS("TTIPCONC"),
	TIPOS_PERSONA("TTIPOPERSONA"),
	TIPOS_PAGO_POLIZA("TPERPAG"),
	TIPOS_PAGO_POLIZA_SIN_DXN("TPERPAG_NODXN"),
	TIPOS_POLIZA("TIPOPOL"),
	TIPSIT("TIPSIT"),
	RAMOS(""),
	ROLES_SISTEMA(""),
	ENDOSOS(""),
	TIPO_PAGO_SINIESTROS("TTIPOPAGO"),
	TIPO_ATENCION_SINIESTROS("TTIPOATENCION"),
	TTRATAMIENTO("TTRATAMIENTO"),
	TPENALIZACIONES("TPENALIZACIONES"),
	PLANES("TPLANES"),
	SINO(""),
	COBERTURAS(""),
	SUBCOBERTURAS(""),
	PROVEEDORES(""),
	MEDICOS(""),
	ICD("2TABLICD"),
	MOTIVOS_RECHAZO_SINIESTRO(""),
	SUBMOTIVOS_RECHAZO_SINIESTRO("")
	;

	private String cdTabla;

	private Catalogos(String cdTabla) {
		this.cdTabla = cdTabla;
	}

	public String getCdTabla() {
		return cdTabla;
	}
}