
package mx.com.gseguros.ws.folioserviciopublico.client.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FolioWS", targetNamespace = "http://com.gs.folioserviciopublico.soap.folio")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FolioWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns mx.com.gseguros.ws.folioserviciopublico.client.jaxws.ResponseFolio
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarFolio", targetNamespace = "http://com.gs.folioserviciopublico.soap.folio", className = "mx.com.gseguros.ws.folioserviciopublico.client.jaxws.ValidarFolio")
    @ResponseWrapper(localName = "validarFolioResponse", targetNamespace = "http://com.gs.folioserviciopublico.soap.folio", className = "mx.com.gseguros.ws.folioserviciopublico.client.jaxws.ValidarFolioResponse")
    public ResponseFolio validarFolio(
        @WebParam(name = "arg0", targetNamespace = "")
        RequestFolio arg0);

}
